# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: sample-wiki
      type: git
      name: confluence-migration-poc

steps:
  - checkout: self
  - checkout: sample-wiki

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'pip3 install beautifulsoup4 pygithub markdown'

  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath'
      scriptPath: '$(System.DefaultWorkingDirectory)/github-wiki-to-html/wiki-generator.py'
      arguments: '-w $(System.DefaultWorkingDirectory)/confluence-migration-poc/ -s stylesheet.css -j script.js -i images -t $(System.DefaultWorkingDirectory)/github-wiki-to-html/webroot/ -r / -p $(github_token)'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/github-wiki-to-html/webroot'
      api_location: 'api'
      output_location: ''
      azure_static_web_apps_api_token: $(deployment_token)
      skip_app_build: true