# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true

- task: Bash@3
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/run.sh'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: $(System.DefaultWorkingDirectory)/webroot
      api_location: 'api'
      output_location: ''
      azure_static_web_apps_api_token: $(deployment_token)