# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: sample-wiki
      type: github
      name: alexander-hjelm/sample-wiki
      endpoint: alexander-hjelm

steps:
  - checkout: self
  - checkout: sample-wiki

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'pip3 install beautifulsoup4 pygithub markdown'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'ls $(System.DefaultWorkingDirectory)'

  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath'
      scriptPath: '$(System.DefaultWorkingDirectory)/wiki-generator.py'
      arguments: '-w /SampleData.wiki/ -s stylesheet.css -j script.js -i images -r $(System.DefaultWorkingDirectory)/webroot/'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: $(System.DefaultWorkingDirectory)/webroot
      api_location: 'api'
      output_location: ''
      azure_static_web_apps_api_token: $(deployment_token)